services:
  pgdb:
    image: postgres:17
    container_name: pgdb
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-U', 'postgres' ]

  pgbouncer:
    container_name: pgbouncer
    image: edoburu/pgbouncer:v1.24.0-p1
    restart: unless-stopped
    depends_on:
      - pgdb
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - DB_HOST=pgdb
      - DB_NAME=${DB_NAME}
      - ADMIN_USERS=postgres
      - POOL_MODE=transaction
      - AUTH_TYPE=scram-sha-256
    volumes:
      - pgbouncer-data:/var/lib/pgbouncer
    healthcheck:
      test: [ 'CMD', 'pg_isready', '-h', 'localhost' ]

  redis:
    image: redis:8.2
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - .env

  app:
    build: .
    container_name: app
    depends_on:
      - pgbouncer
      - redis
    entrypoint:
      - ./bin/entrypoint.sh
    volumes:
      - .:/application
    env_file:
      - .env
    logging:
      driver: json-file

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail-config.yaml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    privileged: true

    loki:
      image: grafana/loki:latest
      container_name: loki
      ports:
        - "3100:3100"
      volumes:
        - ./loki-config.yaml:/etc/loki/local-config.yaml

    prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      ports:
        - "9090:9090"
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
        - prometheusdata:/prometheus

    grafana:
      image: grafana/grafana:latest
      container_name: grafana
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_USER=admin
        - GF_SECURITY_ADMIN_PASSWORD=admin
      volumes:
        - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
        - grafanadata:/var/lib/grafana

volumes:
  postgres-data:
  pgbouncer-data:
  redis-data: