"""Add referal

Revision ID: 9ef4edc6c131
Revises: fd9dc718a068
Create Date: 2025-10-11 23:22:26.689175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef4edc6c131'
down_revision: Union[str, Sequence[str], None] = 'fd9dc718a068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'subscription_period')
    op.add_column('users', sa.Column('referrer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['referrer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referrer_id')
    op.add_column('payments', sa.Column('subscription_period', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
